svg_icon_subset:
  default: "receipt"

topic_map_type:
  default: "static bottom"
  type: enum
  choices:
    - "sticky top"
    - "sticky bottom"
    - "static bottom"

simplified_map:
  default: true
